/***************************************************
TABLA CLIENTE
****************************************************/

CREATE TABLE CLIENTE(
ID_CLIENTE INT,
MIEMBRO_COMUNIDAD VARCHAR(1),
TIPO_CLIENTE CHAR(32),
NOMBRE_CLIENTE CHAR(32),
EDAD INT
);


ALTER TABLE CLIENTE
MODIFY ID_CLIENTE INT NOT NULL;

ALTER TABLE CLIENTE
MODIFY MIEMBRO_COMUNIDAD VARCHAR(1) NOT NULL;

ALTER TABLE CLIENTE
MODIFY TIPO_CLIENTE CHAR(32) NOT NULL;

ALTER TABLE CLIENTE
MODIFY NOMBRE_CLIENTE CHAR(32) NOT NULL;

ALTER TABLE CLIENTE
MODIFY EDAD INT NOT NULL;

ALTER TABLE CLIENTE
ADD CONSTRAINT CK_EDAD CHECK (EDAD >= 18);

ALTER TABLE CLIENTE
ADD PRIMARY KEY(ID_CLIENTE);



/***************************************************
TABLA RESERVA
****************************************************/

CREATE TABLE RESERVA(
ID_RESERVA INT,
CONFIRMADA VARCHAR(1),
FECHA DATE,
TIEMPO_CANCELACION TIMESTAMP WITH LOCAL TIME ZONE,
VALOR FLOAT,
ID_HOTEL INT,
ID_VIVIENDAU INT,
ID_PERSONA INT,
ID_HOSTAL INT,
ID_CLIENTE INT
)

ALTER TABLE RESERVA
MODIFY ID_RESERVA INT NOT NULL;

ALTER TABLE RESERVA
MODIFY FECHA VARCHAR(32);

ALTER TABLE RESERVA
MODIFY TIEMPO_CANCELACION VARCHAR(32);

ALTER TABLE RESERVA
MODIFY CONFIRMADA VARCHAR(1) NOT NULL;


ALTER TABLE RESERVA
MODIFY VALOR FLOAT NOT NULL;

ALTER TABLE RESERVA
MODIFY ID_HOTEL INT NULL;

ALTER TABLE RESERVA
MODIFY ID_VIVIENDAU INT NULL;

ALTER TABLE RESERVA
MODIFY ID_PERSONA INT NULL;

ALTER TABLE RESERVA
MODIFY ID_HOSTAL INT NULL;

ALTER TABLE RESERVA
MODIFY ID_CLIENTE INT NOT NULL;




ALTER TABLE RESERVA
ADD PRIMARY KEY(ID_RESERVA);




ALTER TABLE RESERVA
ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL;

ALTER TABLE RESERVA
ADD FOREIGN KEY (ID_VIVIENDAU) REFERENCES VIVIENDA_UNIVERSITARIA;

ALTER TABLE RESERVA
ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA_NATURAL;

ALTER TABLE RESERVA
ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL;

ALTER TABLE RESERVA
ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE;


/***************************************************
TABLA OFERTA
****************************************************/
CREATE TABLE OFERTA(
ID_OFERTA INT,
NUM_RESERVAS INT,
ID_HOSTAL INT,
ID_HOTEL INT,
ID_VIVIENDAU INT,
ID_PERSONA INT
);


ALTER TABLE OFERTA
MODIFY ID_OFERTA INT NOT NULL;

ALTER TABLE OFERTA
MODIFY NUM_RESERVAS INT NOT NULL;

ALTER TABLE OFERTA
ADD CONSTRAINT CK_NUMRESERVAS CHECK (NUM_RESERVAS>= 0);




ALTER TABLE OFERTA
ADD PRIMARY KEY(ID_OFERTA);




ALTER TABLE OFERTA
ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL;

ALTER TABLE OFERTA
MODIFY ID_HOSTAL DEFAULT NULL;

ALTER TABLE OFERTA
ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL ;

ALTER TABLE OFERTA
MODIFY ID_HOTEL DEFAULT NULL;

ALTER TABLE OFERTA
ADD FOREIGN KEY (ID_VIVIENDAU) REFERENCES VIVIENDA_UNIVERSITARIA;

ALTER TABLE OFERTA
MODIFY ID_VIVIENDAU DEFAULT NULL;

ALTER TABLE OFERTA
ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA_NATURAL;

ALTER TABLE OFERTA
MODIFY ID_PERSONA DEFAULT NULL;



/***************************************************
TABLA SALA
****************************************************/
CREATE TABLE SALA(
ID_SALA INT,
COSTO FLOAT,
PROPOSITO VARCHAR(150),
TIENE_COSTO_ADICIONAL VARCHAR(1),
ID_VIVIENDAU INT
);

ALTER TABLE SALA
MODIFY ID_SALA INT NOT NULL;


ALTER TABLE SALA
MODIFY COSTO FLOAT NOT NULL;

ALTER TABLE SALA
MODIFY PROPOSITO VARCHAR(150) NOT NULL;


ALTER TABLE SALA
MODIFY TIENE_COSTO_ADICIONAL VARCHAR(1) NOT NULL;

ALTER TABLE SALA
MODIFY ID_VIVIENDAU INT NOT NULL;



ALTER TABLE SALA
ADD PRIMARY KEY(ID_SALA);




ALTER TABLE SALA
ADD FOREIGN KEY (ID_VIVIENDAU) REFERENCES VIVIENDA_UNIVERSITARIA;


/***************************************************
TABLA VIVIENDA UNIVERSITARIA
****************************************************/

CREATE TABLE VIVIENDA_UNIVERSITARIA(
ID_VIVIENDAU INT,
AMOBLAMIENTO VARCHAR(1),
CAPACIDAD_VIVIENDAU INT,
DURACION_SERVICIO FLOAT,
CAMARA_COMERCIO VARCHAR(1),
SUPERINTENDENCIA_TURISMO VARCHAR(1),
NOMBRE VARCHAR(32)
);

ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY ID_VIVIENDAU INT NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY AMOBLAMIENTO VARCHAR(1) NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY CAPACIDAD_VIVIENDAU INT NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY DURACION_SERVICIO FLOAT NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY CAMARA_COMERCIO VARCHAR(1) NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY SUPERINTENDENCIA_TURISMO VARCHAR(1) NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
MODIFY NOMBRE VARCHAR(32) NOT NULL;


ALTER TABLE VIVIENDA_UNIVERSITARIA
ADD CONSTRAINT CK_CAPACIDAD CHECK (CAPACIDAD_VIVIENDAU >= 0);


ALTER TABLE VIVIENDA_UNIVERSITARIA
ADD CONSTRAINT CK_DURACION CHECK (DURACION_SERVICIO >= 0);


ALTER TABLE VIVIENDA_UNIVERSITARIA
ADD PRIMARY KEY(ID_VIVIENDAU);


/***************************************************
TABLA HABITACION
****************************************************/

CREATE TABLE HABITACION(
ID_HABITACION INT,
CAPACIDAD_HABITACION INT,
PRECIO FLOAT,
TAMANIO FLOAT,
TIPO VARCHAR(32),
UBICACION VARCHAR(32),
ID_RESERVA INT,
ID_OFERTA INT,
ID_HOTEL INT,
ID_HOSTAL INT,
ID_PERSONA INT,
ID_VIVIENDAU INT
);


ALTER TABLE HABITACION
MODIFY ID_HABITACION INT NOT NULL;

ALTER TABLE HABITACION
MODIFY CAPACIDAD_HABITACION INT NOT NULL;

ALTER TABLE HABITACION
MODIFY PRECIO FLOAT NOT NULL;

ALTER TABLE HABITACION
MODIFY TAMANIO FLOAT NOT NULL;

ALTER TABLE HABITACION
MODIFY TIPO VARCHAR(32) NOT NULL;


ALTER TABLE HABITACION
ADD CONSTRAINT CK_CAPACIDADH CHECK (CAPACIDAD_HABITACION >= 0);

ALTER TABLE HABITACION
ADD CONSTRAINT CK_PRECIOH CHECK (PRECIO >= 0);

ALTER TABLE HABITACION
ADD CONSTRAINT CK_TAMANIOH CHECK (TAMANIO >= 0);



ALTER TABLE HABITACION
ADD PRIMARY KEY(ID_HABITACION);



ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA;

ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_OFERTA) REFERENCES OFERTA;

ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL;

ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_HOSTAL) REFERENCES HOSTAL;

ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA_NATURAL;

ALTER TABLE HABITACION
ADD FOREIGN KEY (ID_VIVIENDAU) REFERENCES VIVIENDA_UNIVERSITARIA;



/***************************************************
TABLA HOSTAL
****************************************************/

CREATE TABLE HOSTAL(
ID_HOSTAL INT,
CAPACIDAD_HOSTAL INT,
HORA_APERTURA VARCHAR(32),
HORA_CIERRE VARCHAR(32),
RECEPCION24_HORAS VARCHAR(1),
CAMARA_COMERCIO VARCHAR(1),
SUPERINTENDENCIA_TURISMO VARCHAR(1),
NOMBRE VARCHAR(32)
);


ALTER TABLE HOSTAL
MODIFY ID_HOSTAL INT NOT NULL;


ALTER TABLE HOSTAL
MODIFY CAPACIDAD_HOSTAL INT NOT NULL;


ALTER TABLE HOSTAL
MODIFY HORA_APERTURA VARCHAR(32) NOT NULL;

ALTER TABLE HOSTAL
MODIFY HORA_CIERRE VARCHAR(32) NOT NULL;

ALTER TABLE HOSTAL
MODIFY RECEPCION24_HORAS VARCHAR(1) NOT NULL;

ALTER TABLE HOSTAL
MODIFY CAMARA_COMERCIO VARCHAR(1) NOT NULL;

ALTER TABLE HOSTAL
MODIFY SUPERINTENDENCIA_TURISMO VARCHAR(1) NOT NULL;

ALTER TABLE HOSTAL
MODIFY NOMBRE VARCHAR(32) NOT NULL;

ALTER TABLE HOSTAL
ADD CONSTRAINT CK_CAPACIDADTAL CHECK (CAPACIDAD_HOSTAL >= 0);




ALTER TABLE HOSTAL
ADD PRIMARY KEY(ID_HOSTAL);


/***************************************************
TABLA HOTEL
****************************************************/

CREATE TABLE HOTEL(
ID_HOTEL INT,
CAPACIDAD_HOTEL INT,
CAMARA_COMERCIO VARCHAR(1),
SUPERINTENDENCIA_TURISMO VARCHAR(1),
NOMBRE VARCHAR(32)
);


ALTER TABLE HOTEL
MODIFY ID_HOTEL INT NOT NULL;

ALTER TABLE HOTEL
MODIFY CAPACIDAD_HOTEL INT NOT NULL;

ALTER TABLE HOTEL
MODIFY CAMARA_COMERCIO VARCHAR(1) NOT NULL;

ALTER TABLE HOTEL
MODIFY SUPERINTENDENCIA_TURISMO VARCHAR(1) NOT NULL;

ALTER TABLE HOTEL
MODIFY NOMBRE VARCHAR(32) NOT NULL;

ALTER TABLE HOTEL
ADD CONSTRAINT CK_CAPACIDADTEL CHECK (CAPACIDAD_HOTEL >= 0);




ALTER TABLE HOTEL
ADD PRIMARY KEY(ID_HOTEL);



/***************************************************
TABLA PERSONA NATURAL
****************************************************/

CREATE TABLE PERSONA_NATURAL(
ID_PERSONA INT,
EDAD INT,
MIEMBRO_COMUNIDAD VARCHAR(1),
CAMARA_COMERCIO VARCHAR(1),
SUPERINTENDENCIA_TURISMO VARCHAR(1),
NOMBRE VARCHAR(32)
);


ALTER TABLE PERSONA_NATURAL
MODIFY ID_PERSONA INT NOT NULL;

ALTER TABLE PERSONA_NATURAL
MODIFY EDAD INT NOT NULL;

ALTER TABLE PERSONA_NATURAL
MODIFY MIEMBRO_COMUNIDAD VARCHAR(1) NOT NULL;

ALTER TABLE PERSONA_NATURAL
MODIFY CAMARA_COMERCIO VARCHAR(1) NOT NULL;

ALTER TABLE PERSONA_NATURAL
MODIFY SUPERINTENDENCIA_TURISMO VARCHAR(1) NOT NULL;

ALTER TABLE PERSONA_NATURAL
MODIFY NOMBRE VARCHAR(32) NOT NULL;

ALTER TABLE PERSONA_NATURAL
ADD CONSTRAINT CK_EDADPERS CHECK (EDAD >= 18);




ALTER TABLE PERSONA_NATURAL
ADD PRIMARY KEY(ID_PERSONA);


/***************************************************
TABLA APARTAMENTO
****************************************************/

CREATE TABLE APARTAMENTO(
ID_APARTAMENTO INT,
AMOBLADO VARCHAR(1),
CAPACIDAD_APTO INT,
PRECIO_APTO INT,
ID_PERSONA INT,
ID_OFERTA INT
);


ALTER TABLE APARTAMENTO
MODIFY ID_APARTAMENTO INT NOT NULL;

ALTER TABLE APARTAMENTO
MODIFY AMOBLADO VARCHAR(1) NOT NULL;

ALTER TABLE APARTAMENTO
MODIFY CAPACIDAD_APTO INT NOT NULL;

ALTER TABLE APARTAMENTO
MODIFY PRECIO_APTO INT NOT NULL;

ALTER TABLE APARTAMENTO
MODIFY ID_PERSONA INT NOT NULL;

ALTER TABLE APARTAMENTO
ADD CONSTRAINT CK_CAPAPTO CHECK (CAPACIDAD_APTO >= 0);

ALTER TABLE APARTAMENTO
ADD CONSTRAINT CK_PRECIOAPTO CHECK (PRECIO_APTO >= 0);



ALTER TABLE APARTAMENTO
ADD PRIMARY KEY(ID_APARTAMENTO);




ALTER TABLE APARTAMENTO
ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA_NATURAL;

ALTER TABLE APARTAMENTO
ADD FOREIGN KEY (ID_OFERTA) REFERENCES OFERTA;


/***************************************************
TABLA VIVIENDA
****************************************************/

CREATE TABLE VIVIENDA(
ID_VIVIENDA INT,
CARACTERISTICAS_SEGURO VARCHAR(150),
CARACTERISTICAS_VIVIENDA VARCHAR(150),
PRECIO_VIVIENDA INT,
ID_VECINO INT
);

ALTER TABLE VIVIENDA
MODIFY ID_VIVIENDA INT NOT NULL;


ALTER TABLE VIVIENDA
MODIFY CARACTERISTICAS_VIVIENDA VARCHAR(150) NOT NULL;

ALTER TABLE VIVIENDA
MODIFY PRECIO_VIVIENDA INT NOT NULL;

ALTER TABLE VIVIENDA
MODIFY ID_VECINO INT NOT NULL;

ALTER TABLE VIVIENDA
ADD CONSTRAINT CK_PRECIOVIV CHECK (PRECIO_VIVIENDA >= 0);

ALTER TABLE VIVIENDA
ADD PRIMARY KEY(ID_VIVIENDA);


ALTER TABLE VIVIENDA
ADD FOREIGN KEY (ID_VECINO) REFERENCES VECINO;
 

/***************************************************
TABLA SERVICIO PUBLICO
****************************************************/

CREATE TABLE SERVICIO_PUBLICO(
ID_SERVICIO_PUBLICO INT,
TIPO_SERVICIO_PUBLICO VARCHAR(32),
COSTO_SERVICIO_PUBLICO FLOAT
);

ALTER TABLE SERVICIO_PUBLICO
MODIFY ID_SERVICIO_PUBLICO INT NOT NULL;

ALTER TABLE SERVICIO_PUBLICO
MODIFY TIPO_SERVICIO_PUBLICO VARCHAR(32) NOT NULL;

ALTER TABLE SERVICIO_PUBLICO
MODIFY COSTO_SERVICIO_PUBLICO FLOAT NOT NULL;

ALTER TABLE SERVICIO_PUBLICO
ADD CONSTRAINT CK_COSTOSP CHECK (COSTO_SERVICIO_PUBLICO >= 0);


ALTER TABLE SERVICIO_PUBLICO 
ADD PRIMARY KEY(ID_SERVICIO_PUBLICO);



/***************************************************
TABLA SERVICIO INMOBILIARIO
****************************************************/
CREATE TABLE SERVICIO_INMOBILIARIO(
ID_SERVICIO_INMOBILIARIO INT,
TIPO_SERVICIO_INMOBILIARIO VARCHAR(32),
COSTO_SERVICIO_INMOBILIARIO FLOAT
);

ALTER TABLE SERVICIO_INMOBILIARIO
MODIFY ID_SERVICIO_INMOBILIARIO INT NOT NULL;

ALTER TABLE SERVICIO_INMOBILIARIO
MODIFY TIPO_SERVICIO_INMOBILIARIO VARCHAR(32) NOT NULL;

ALTER TABLE SERVICIO_INMOBILIARIO
MODIFY COSTO_SERVICIO_INMOBILIARIO FLOAT NOT NULL;

ALTER TABLE SERVICIO_INMOBILIARIO
ADD CONSTRAINT CK_COSTOSI CHECK (COSTO_SERVICIO_INMOBILIARIO >= 0);

ALTER TABLE SERVICIO_INMOBILIARIO
ADD PRIMARY KEY(ID_SERVICIO_INMOBILIARIO);



/***************************************************
TABLA VECINO
****************************************************/
CREATE TABLE VECINO(
ID_VECINO INT,
EDAD INT,
ID_PERSONA INT,
MIEMBRO_COMUNIDAD VARCHAR(1),
CAMARA_COMERCIO VARCHAR(1),
SUPERINTENDENCIA_TURISMO VARCHAR(1),
NOMBRE VARCHAR(32)
);

ALTER TABLE VECINO
MODIFY ID_VECINO INT NOT NULL;

ALTER TABLE VECINO
MODIFY EDAD INT NOT NULL;

ALTER TABLE VECINO
MODIFY ID_PERSONA INT NOT NULL;

ALTER TABLE VECINO
MODIFY MIEMBRO_COMUNIDAD VARCHAR(1) NOT NULL;

ALTER TABLE VECINO
MODIFY CAMARA_COMERCIO VARCHAR(1) NOT NULL;

ALTER TABLE VECINO
MODIFY SUPERINTENDENCIA_TURISMO VARCHAR(1) NOT NULL;

ALTER TABLE VECINO
MODIFY NOMBRE VARCHAR(32) NOT NULL;

ALTER TABLE VECINO
ADD CONSTRAINT CK_EDADV CHECK (EDAD >= 18);


ALTER TABLE VECINO
ADD PRIMARY KEY(ID_VECINO);


/***************************************************
TABLA HABITACIONES Y SERVICIOS PUBLICOS
****************************************************/
CREATE TABLE HABITACIONES_SERVICIOSPUBLICOS(
ID_HABITACION INT,
ID_SERVICIO_PUBLICO INT
);

ALTER TABLE HABITACIONES_SERVICIOSPUBLICOS
ADD PRIMARY KEY( ID_HABITACION, ID_SERVICIO_PUBLICO);


ALTER TABLE HABITACIONES_SERVICIOSPUBLICOS
ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION;

ALTER TABLE HABITACIONES_SERVICIOSPUBLICOS
ADD FOREIGN KEY (ID_SERVICIO_PUBLICO) REFERENCES SERVICIO_PUBLICO;

/***************************************************
TABLA HABITACIONES Y SERVICIOS INMOBILIARIOS
****************************************************/

CREATE TABLE HABITACIONES_INMOBILIARIOS(
ID_HABITACION INT,
ID_SERVICIO_INMOBILIARIO INT
);

ALTER TABLE HABITACIONES_INMOBILIARIOS
ADD PRIMARY KEY( ID_HABITACION, ID_SERVICIO_INMOBILIARIO);


ALTER TABLE HABITACIONES_INMOBILIARIOS
ADD FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION;

ALTER TABLE HABITACIONES_INMOBILIARIOS
ADD FOREIGN KEY (ID_SERVICIO_INMOBILIARIO) REFERENCES SERVICIO_INMOBILIARIO;

