/***************************************************
MOSTRAR EL DINERO RECIBIDO POR CADA PROVEEDOR
****************************************************/

SELECT ID_HOTEL, VALOR
FROM RESERVA
WHERE ID_HOTEL IS NOT NULL AND CONFIRMADA = 'T';

SELECT ID_HOSTAL, VALOR
FROM RESERVA
WHERE ID_HOSTAL IS NOT NULL AND CONFIRMADA = 'T';

SELECT ID_PERSONA, VALOR
FROM RESERVA
WHERE ID_PERSONA IS NOT NULL AND CONFIRMADA = 'T';

SELECT ID_VIVIENDAU, VALOR
FROM RESERVA
WHERE ID_VIVIENDAU IS NOT NULL AND CONFIRMADA = 'T';

/***************************************************
MOSTRAR LAS 20 OFERTAS MAS POPULARES
****************************************************/

SELECT *
FROM (SELECT *
      FROM OFERTA
      ORDER BY NUM_RESERVAS DESC)
WHERE ROWNUM <= 20;
